.TH "Blacklist" 3 "10 May 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blacklist \- Contains the blocked numbers.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libphonefirewall.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "long long int \fBnumber\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "char * \fBreason\fP"
.br
.ti -1c
.RI "struct \fBBlacklist\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBBlacklist\fP * \fBright\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the blocked numbers. 
.PP
Definition at line 42 of file libphonefirewall.h.
.SH "Field Documentation"
.PP 
.SS "char* \fBBlacklist::name\fP"
.PP
Definition at line 43 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().
.SS "long long int \fBBlacklist::number\fP"
.PP
Definition at line 44 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().
.SS "int \fBBlacklist::priority\fP"
.PP
Definition at line 45 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().
.SS "char* \fBBlacklist::reason\fP"
.PP
Definition at line 46 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().
.SS "struct \fBBlacklist\fP* \fBBlacklist::left\fP\fC [read]\fP"
.PP
Definition at line 47 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().
.SS "struct \fBBlacklist\fP* \fBBlacklist::right\fP\fC [read]\fP"
.PP
Definition at line 48 of file libphonefirewall.h.
.PP
Referenced by add_to_blacklist().

.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
