.TH "Entry" 3 "14 Jul 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <libphonefirewall.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcountry_code\fP"
.br
.ti -1c
.RI "int \fBarea_code\fP"
.br
.ti -1c
.RI "unsigned long long \fBnumber\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBreason\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "struct \fBEntry\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file libphonefirewall.h.
.SH "Field Documentation"
.PP 
.SS "int \fBEntry::country_code\fP"
.PP
Definition at line 59 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry_by_name(), and get_entry_by_name().
.SS "int \fBEntry::area_code\fP"
.PP
Definition at line 60 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry_by_name(), and get_entry_by_name().
.SS "unsigned long long \fBEntry::number\fP"
.PP
Definition at line 61 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry_by_name(), and get_entry_by_name().
.SS "char* \fBEntry::name\fP"
.PP
Definition at line 62 of file libphonefirewall.h.
.PP
Referenced by find_entry_by_name().
.SS "char* \fBEntry::reason\fP"
.PP
Definition at line 63 of file libphonefirewall.h.
.PP
Referenced by find_entry_by_name(), and get_entry_by_name().
.SS "int \fBEntry::priority\fP"
.PP
Definition at line 64 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), and find_entry_by_name().
.SS "struct \fBEntry\fP* \fBEntry::next\fP\fC [read]\fP"
.PP
Definition at line 65 of file libphonefirewall.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
