.TH "Entry" 3 "19 Dec 2008" "Version v0.02" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <libphonefirewall.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcountry_code\fP"
.br
.ti -1c
.RI "int \fBarea_code\fP"
.br
.ti -1c
.RI "unsigned long long \fBnumber\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBreason\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "struct \fBEntry\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file libphonefirewall.h.
.SH "Field Documentation"
.PP 
.SS "int \fBEntry::country_code\fP"
.PP
Definition at line 65 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry(), and insert_into_list().
.SS "int \fBEntry::area_code\fP"
.PP
Definition at line 66 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry(), and insert_into_list().
.SS "unsigned long long \fBEntry::number\fP"
.PP
Definition at line 67 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), find_entry(), and insert_into_list().
.SS "char* \fBEntry::name\fP"
.PP
Definition at line 68 of file libphonefirewall.h.
.PP
Referenced by find_entry(), and insert_into_list().
.SS "char* \fBEntry::reason\fP"
.PP
Definition at line 69 of file libphonefirewall.h.
.PP
Referenced by find_entry(), and insert_into_list().
.SS "int \fBEntry::priority\fP"
.PP
Definition at line 70 of file libphonefirewall.h.
.PP
Referenced by check_entry(), evaluate_stmt(), and find_entry().
.SS "struct \fBEntry\fP* \fBEntry::next\fP\fC [read]\fP"
.PP
Definition at line 71 of file libphonefirewall.h.
.PP
Referenced by insert_into_list().

.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
