.TH "entry" 3 "13 Jul 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entry \- Includes all informations for an \fBentry\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libphonefirewall.h>\fP
.PP
.SH "Detailed Description"
.PP 
Includes all informations for an \fBentry\fP. 

The struct which includes all information about entries (black- and whitelist). 

.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
