libphonefirewall.h
NAME
libphonefirewall.h - API of the phone firewall.
SYNOPSIS
Data Structures
struct entry
Includes all informations for an entry.
Defines
#define MAX_LINE_LENGTH 512
Functions
int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)
int rm_blacklist_entry (unsigned long long number)
char * check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)
int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)
struct entry * get_blacklist_entry_by_name (char *name)
struct entry * get_blacklist_entry_by_number (int country_code, int area_code, unsigned long long number)
int rm_whitelist_entry (unsigned long long number)
char * check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)
struct entry * get_whitelist_entry_by_name (char *name)
struct entry * get_whitelist_entry_by_number (int country_code, int area_code, unsigned long long number)
Detailed Description
API of the phone firewall.
Author:
Alex Oberhauser
The header file of the Phone Firewall. Blocks or accepts incoming phone calls, so it's possible to prevent disturbing phone calls. Provides a API which can used by other application to build nice programs.
Implemented for the OpenMoko framework.
Definition in file libphonefirewall.h.
Define Documentation
#define MAX_LINE_LENGTH 512
Definition at line 33 of file libphonefirewall.h.
Referenced by check_blacklist_entry(), and check_whitelist_entry().
Function Documentation
int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)
Add a number to the blacklist. The number will be blocked after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If all goes well 0 (zero) otherwise an errno code.
Definition at line 40 of file phonefirewall_administration.c.
References BLACKLIST_PREFIX, DELIM, filename, and set_filename().
int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)
Add a number to the whitelist. The number will be accepted after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If all goes well 0 (zero) otherwise an errno code.
Definition at line 54 of file phonefirewall_administration.c.
References DELIM, filename, set_filename(), and WHITELIST_PREFIX.
char* check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)
Checks if a number is on the blacklist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If noting is found NULL, otherwise the number.
Definition at line 76 of file phonefirewall_administration.c.
References BLACKLIST_PREFIX, DELIM, filename, MAX_LINE_LENGTH, and set_filename().
char* check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)
Checks if a number is on the whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If noting is found NULL, otherwise the number.
Definition at line 110 of file phonefirewall_administration.c.
References DELIM, filename, MAX_LINE_LENGTH, set_filename(), and WHITELIST_PREFIX.
struct entry* get_blacklist_entry_by_name (char * name) [read]
Search a entrie by name.
Parameters:
name The name of the person which is blocked.
Returns:
entry Returns the found entry.
struct entry* get_blacklist_entry_by_number (int country_code, int area_code, unsigned long long number) [read]
Search a entrie by number (country code + area code + number).
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
Returns:
entry Returns the found entry.
struct entry* get_whitelist_entry_by_name (char * name) [read]
Search a entrie by name.
Parameters:
name The name of the person which is accepted.
Returns:
entry Returns the found entry.
struct entry* get_whitelist_entry_by_number (int country_code, int area_code, unsigned long long number) [read]
Search a entrie by number (country code + area code + number).
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
Returns:
entry Returns the found entry.
int rm_blacklist_entry (unsigned long long number)
Removes a blocked number from the blacklist.
Parameters:
number The number which will be deleted.
Returns:
If all goes right 0, otherwise an error code.
Definition at line 68 of file phonefirewall_administration.c.
int rm_whitelist_entry (unsigned long long number)
Removes a accepted number from the whitelist.
Parameters:
number The number which will be deleted.
Returns:
If all goes right 0, otherwise an error code.
Definition at line 72 of file phonefirewall_administration.c.
Author
Generated automatically by Doxygen for Phone Firewall from the source code.