.TH "libphonefirewall.h" 3 "2 Oct 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libphonefirewall.h \- API of the phone firewall. 
.SH SYNOPSIS
.br
.PP
\fC#include 'pf_search.h'\fP
.br
\fC#include 'pf_administration.h'\fP
.br
\fC#include 'logfile.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEntry\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPRIO_ALL\fP   -999"
.br
.ti -1c
.RI "#define \fBDB_FILE\fP   'db/phone-firewall.db'"
.br
.ti -1c
.RI "#define \fBSTMT_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_LINE_LENGTH\fP   512"
.br
.ti -1c
.RI "#define \fBTB_COUNTRYCODE\fP   'countrycode'"
.br
.ti -1c
.RI "#define \fBTB_AREACODE\fP   'areacode'"
.br
.ti -1c
.RI "#define \fBTB_NUMBER\fP   'number'"
.br
.ti -1c
.RI "#define \fBTB_NAME\fP   'name'"
.br
.ti -1c
.RI "#define \fBTB_REASON\fP   'reason'"
.br
.ti -1c
.RI "#define \fBTB_PRIORITY\fP   'priority'"
.br
.ti -1c
.RI "#define \fBBLACKLIST_FLAG\fP   0x01"
.br
.ti -1c
.RI "#define \fBWHITELIST_FLAG\fP   0x02"
.br
.ti -1c
.RI "#define \fBCOMPONENT_NAME\fP   'phone firewall'"
.br
.in -1c
.SH "Detailed Description"
.PP 
API of the phone firewall. 

\fBAuthor:\fP
.RS 4
Alex Oberhauser
.RE
.PP
The header file of the Phone Firewall. Blocks or accepts incoming phone calls, so it's possible to prevent disturbing phone calls. Provides a API which can used by other application to build nice programs. 
.PP
Definition in file \fBlibphonefirewall.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define BLACKLIST_FLAG   0x01"
.PP
Definition at line 49 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define COMPONENT_NAME   'phone firewall'"
.PP
Definition at line 52 of file libphonefirewall.h.
.SS "#define DB_FILE   'db/phone-firewall.db'"
.PP
Definition at line 38 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define MAX_LINE_LENGTH   512"
.PP
Definition at line 40 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define PRIO_ALL   -999"
.PP
Definition at line 37 of file libphonefirewall.h.
.PP
Referenced by add_entry(), and evaluate_stmt().
.SS "#define STMT_SIZE   1024"
.PP
Definition at line 39 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define TB_AREACODE   'areacode'"
.PP
Definition at line 43 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), evaluate_stmt(), find_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define TB_COUNTRYCODE   'countrycode'"
.PP
Definition at line 42 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), evaluate_stmt(), find_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define TB_NAME   'name'"
.PP
Definition at line 45 of file libphonefirewall.h.
.PP
Referenced by add_entry(), find_entry(), get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
.SS "#define TB_NUMBER   'number'"
.PP
Definition at line 44 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), evaluate_stmt(), find_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SS "#define TB_PRIORITY   'priority'"
.PP
Definition at line 47 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), evaluate_stmt(), find_entry(), get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
.SS "#define TB_REASON   'reason'"
.PP
Definition at line 46 of file libphonefirewall.h.
.PP
Referenced by add_entry(), find_entry(), get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
.SS "#define WHITELIST_FLAG   0x02"
.PP
Definition at line 50 of file libphonefirewall.h.
.PP
Referenced by add_entry(), check_entry(), get_entry_by_name(), get_entry_by_number(), get_entry_by_reason(), and rm_entry().
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
