.TH "libphonefirewall.h" 3 "7 Jun 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libphonefirewall.h \- API of the phone firewall. 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEntry\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPRIO_ALL\fP   -999"
.br
.ti -1c
.RI "#define \fBDB_FILE\fP   'db/phone-firewall.db'"
.br
.ti -1c
.RI "#define \fBSTMT_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_LINE_LENGTH\fP   512"
.br
.ti -1c
.RI "#define \fBTB_COUNTRYCODE\fP   'countrycode'"
.br
.ti -1c
.RI "#define \fBTB_AREACODE\fP   'areacode'"
.br
.ti -1c
.RI "#define \fBTB_NUMBER\fP   'number'"
.br
.ti -1c
.RI "#define \fBTB_NAME\fP   'name'"
.br
.ti -1c
.RI "#define \fBTB_REASON\fP   'reason'"
.br
.ti -1c
.RI "#define \fBTB_PRIORITY\fP   'priority'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBadd_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "int \fBrm_blacklist_entry\fP (int country_code, int area_code, unsigned long long number)"
.br
.ti -1c
.RI "int \fBcheck_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.ti -1c
.RI "int \fBadd_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "struct \fBentry\fP * \fBget_blacklist_entry_by_name\fP (char *name)"
.br
.ti -1c
.RI "struct \fBentry\fP * \fBget_blacklist_entry_by_number\fP (int country_code, int area_code, unsigned long long number)"
.br
.ti -1c
.RI "int \fBrm_whitelist_entry\fP (int country_code, int area_code, unsigned long long number)"
.br
.ti -1c
.RI "int \fBcheck_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.ti -1c
.RI "struct \fBentry\fP * \fBget_whitelist_entry_by_name\fP (char *name)"
.br
.ti -1c
.RI "struct \fBentry\fP * \fBget_whitelist_entry_by_number\fP (int country_code, int area_code, unsigned long long number)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBEntry\fP \fBentry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
API of the phone firewall. 

\fBAuthor:\fP
.RS 4
Alex Oberhauser
.RE
.PP
The header file of the Phone Firewall. Blocks or accepts incoming phone calls, so it's possible to prevent disturbing phone calls. Provides a API which can used by other application to build nice programs. 
.PP
Definition in file \fBlibphonefirewall.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define DB_FILE   'db/phone-firewall.db'"
.PP
Definition at line 33 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), rm_blacklist_entry(), and rm_whitelist_entry().
.SS "#define MAX_LINE_LENGTH   512"
.PP
Definition at line 35 of file libphonefirewall.h.
.SS "#define PRIO_ALL   -999"
.PP
Definition at line 32 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), and evaluate_stmt().
.SS "#define STMT_SIZE   1024"
.PP
Definition at line 34 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), rm_blacklist_entry(), and rm_whitelist_entry().
.SS "#define TB_AREACODE   'areacode'"
.PP
Definition at line 38 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), evaluate_stmt(), rm_blacklist_entry(), and rm_whitelist_entry().
.SS "#define TB_COUNTRYCODE   'countrycode'"
.PP
Definition at line 37 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), evaluate_stmt(), rm_blacklist_entry(), and rm_whitelist_entry().
.SS "#define TB_NAME   'name'"
.PP
Definition at line 40 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), and add_whitelist_entry().
.SS "#define TB_NUMBER   'number'"
.PP
Definition at line 39 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), evaluate_stmt(), rm_blacklist_entry(), and rm_whitelist_entry().
.SS "#define TB_PRIORITY   'priority'"
.PP
Definition at line 42 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), and evaluate_stmt().
.SS "#define TB_REASON   'reason'"
.PP
Definition at line 41 of file libphonefirewall.h.
.PP
Referenced by add_blacklist_entry(), and add_whitelist_entry().
.SH "Function Documentation"
.PP 
.SS "int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the blacklist. The number will be blocked after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen. 
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 73 of file phonefirewall_administration.c.
.PP
References DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
.SS "int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the whitelist. The number will be accepted after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 108 of file phonefirewall_administration.c.
.PP
References DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
.SS "int check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 210 of file phonefirewall_administration.c.
.PP
References Entry::area_code, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.SS "int check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 261 of file phonefirewall_administration.c.
.PP
References Entry::area_code, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.SS "struct \fBentry\fP* get_blacklist_entry_by_name (char * name)\fC [read]\fP"
.PP
Search a entrie by name.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name of the person which is blocked.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBentry\fP Returns the found \fBentry\fP. 
.RE
.PP

.PP
Definition at line 27 of file phonefirewall_search.c.
.SS "struct \fBentry\fP* get_blacklist_entry_by_number (int country_code, int area_code, unsigned long long number)\fC [read]\fP"
.PP
Search a entrie by number (country code + area code + number).
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBentry\fP Returns the found \fBentry\fP. 
.RE
.PP

.PP
Definition at line 30 of file phonefirewall_search.c.
.SS "struct \fBentry\fP* get_whitelist_entry_by_name (char * name)\fC [read]\fP"
.PP
Search a entrie by name.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name of the person which is accepted.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBentry\fP Returns the found \fBentry\fP. 
.RE
.PP

.PP
Definition at line 33 of file phonefirewall_search.c.
.SS "struct \fBentry\fP* get_whitelist_entry_by_number (int country_code, int area_code, unsigned long long number)\fC [read]\fP"
.PP
Search a entrie by number (country code + area code + number).
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBentry\fP Returns the found \fBentry\fP. 
.RE
.PP

.PP
Definition at line 36 of file phonefirewall_search.c.
.SS "int rm_blacklist_entry (int country_code, int area_code, unsigned long long number)"
.PP
Removes a blocked number from the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 143 of file phonefirewall_administration.c.
.PP
References DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, and TB_NUMBER.
.SS "int rm_whitelist_entry (int country_code, int area_code, unsigned long long number)"
.PP
Removes a accepted number from the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 176 of file phonefirewall_administration.c.
.PP
References DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, and TB_NUMBER.
.SH "Variable Documentation"
.PP 
.SS "struct \fBEntry\fP  \fBentry\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
