logfile.h
NAME
logfile.h -
SYNOPSIS
Defines
#define LOGFILE 'log/moksec.log'
#define MAX_ENTRY_LENGTH 128
#define UNKNOWN 0
#define ERR_FLAG 1
#define WARN_FLAG 2
#define INFO_FLAG 3
Functions
int write_logentry (char *msg, char *component, int flag)
Define Documentation
#define ERR_FLAG 1
Definition at line 25 of file logfile.h.
Referenced by add_entry(), check_entry(), dbus_listen(), get_entry_by_name(), rm_entry(), and write_logentry().
#define INFO_FLAG 3
Definition at line 27 of file logfile.h.
Referenced by check_entry(), dbus_listen(), start_daemon(), stop_daemon(), and write_logentry().
#define LOGFILE 'log/moksec.log'
Definition at line 21 of file logfile.h.
Referenced by write_logentry().
#define MAX_ENTRY_LENGTH 128
Definition at line 22 of file logfile.h.
Referenced by write_logentry().
#define UNKNOWN 0
Definition at line 24 of file logfile.h.
Referenced by write_logentry().
#define WARN_FLAG 2
Definition at line 26 of file logfile.h.
Referenced by write_logentry().
Function Documentation
int write_logentry (char * msg, char * component, int flag)
Writes a logfile enty.
Parameters:
msg The message which should be written in the logfile.
component The program which calls the write_logentry function, for example 'phonefirewall'
flag What message should be written. Use the defined flags.
Returns:
-1 if something fails, otherwise 0
Definition at line 56 of file logfile.c.
References asctime(), ERR_FLAG, INFO_FLAG, LOGFILE, MAX_ENTRY_LENGTH, UNKNOWN, and WARN_FLAG.
Referenced by add_entry(), check_entry(), dbus_listen(), get_entry_by_name(), rm_entry(), start_daemon(), and stop_daemon().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.