.TH "logfile.c" 3 "12 Nov 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logfile.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include 'logfile.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBasctime\fP (const struct tm *timeptr)"
.br
.ti -1c
.RI "int \fBwrite_logentry\fP (char *msg, char *component, int flag)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* asctime (const struct tm * timeptr)"
.PP
Compounds a humand readable date and time string.
.PP
\fBParameters:\fP
.RS 4
\fItimeptr\fP A pointer to the actual time.
.RE
.PP
\fBReturns:\fP
.RS 4
The date and time as a string. 
.RE
.PP

.PP
Definition at line 33 of file logfile.c.
.PP
Referenced by write_logentry().
.SS "int write_logentry (char * msg, char * component, int flag)"
.PP
Writes a logfile enty.
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP The message which should be written in the logfile. 
.br
\fIcomponent\fP The program which calls the write_logentry function, for example 'phonefirewall' 
.br
\fIflag\fP What message should be written. Use the defined flags.
.RE
.PP
\fBReturns:\fP
.RS 4
-1 if something fails, otherwise 0 
.RE
.PP

.PP
Definition at line 58 of file logfile.c.
.PP
References asctime(), ERR_FLAG, INFO_FLAG, LOGFILE, MAX_ENTRY_LENGTH, UNKNOWN, and WARN_FLAG.
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
