.TH "logfile.h" 3 "14 Jul 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logfile.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOGFILE\fP   'log/moksec.log'"
.br
.ti -1c
.RI "#define \fBMAX_ENTRY_LENGTH\fP   128"
.br
.ti -1c
.RI "#define \fBUNKNOWN\fP   0"
.br
.ti -1c
.RI "#define \fBERR_FLAG\fP   1"
.br
.ti -1c
.RI "#define \fBWARN_FLAG\fP   2"
.br
.ti -1c
.RI "#define \fBINFO_FLAG\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBwrite_logentry\fP (char *msg, char *component, int flag)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ERR_FLAG   1"
.PP
Definition at line 25 of file logfile.h.
.PP
Referenced by add_entry(), check_entry(), dbus_listen(), get_entry_by_name(), rm_entry(), and write_logentry().
.SS "#define INFO_FLAG   3"
.PP
Definition at line 27 of file logfile.h.
.PP
Referenced by check_entry(), dbus_listen(), start_daemon(), stop_daemon(), and write_logentry().
.SS "#define LOGFILE   'log/moksec.log'"
.PP
Definition at line 21 of file logfile.h.
.PP
Referenced by write_logentry().
.SS "#define MAX_ENTRY_LENGTH   128"
.PP
Definition at line 22 of file logfile.h.
.PP
Referenced by write_logentry().
.SS "#define UNKNOWN   0"
.PP
Definition at line 24 of file logfile.h.
.PP
Referenced by write_logentry().
.SS "#define WARN_FLAG   2"
.PP
Definition at line 26 of file logfile.h.
.PP
Referenced by write_logentry().
.SH "Function Documentation"
.PP 
.SS "int write_logentry (char * msg, char * component, int flag)"
.PP
Writes a logfile enty.
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP The message which should be written in the logfile. 
.br
\fIcomponent\fP The program which calls the write_logentry function, for example 'phonefirewall' 
.br
\fIflag\fP What message should be written. Use the defined flags.
.RE
.PP
\fBReturns:\fP
.RS 4
-1 if something fails, otherwise 0 
.RE
.PP

.PP
Definition at line 56 of file logfile.c.
.PP
References asctime(), ERR_FLAG, INFO_FLAG, LOGFILE, MAX_ENTRY_LENGTH, UNKNOWN, and WARN_FLAG.
.PP
Referenced by add_entry(), check_entry(), dbus_listen(), get_entry_by_name(), rm_entry(), start_daemon(), and stop_daemon().
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
