pf_administration.h
NAME
pf_administration.h -
SYNOPSIS
Functions
int add_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority, int listflag)
int rm_entry (int country_code, int area_code, unsigned long long number, int listlfag)
int check_entry (int country_code, int area_code, unsigned long long number, int priority, int listflag)
Function Documentation
int add_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority, int listflag)
Add a number to the blacklist/whitelist. The number will be blocked after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
The value 'PRIO_ALL' stands for all priorities.
Returns:
If all goes well 0 (zero) otherwise -1 and the errno variable will be set..
Definition at line 75 of file pf_administration.c.
References BLACKLIST_FLAG, DB_FILE, ERR_FLAG, MAX_LINE_LENGTH, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, WHITELIST_FLAG, and write_logentry().
int check_entry (int country_code, int area_code, unsigned long long number, int priority, int listflag)
Checks if a number is on the blacklist/whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
The value 'PRIO_ALL' stands for all priorities.
Returns:
If the number was found 1, otherwise 0.
Definition at line 178 of file pf_administration.c.
References Entry::area_code, BLACKLIST_FLAG, Entry::country_code, DB_FILE, ERR_FLAG, evaluate_stmt(), INFO_FLAG, MAX_LINE_LENGTH, Entry::number, p_entry, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, WHITELIST_FLAG, and write_logentry().
int rm_entry (int country_code, int area_code, unsigned long long number, int listlfag)
Removes a number from the blacklist/whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The number which will be deleted.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If all goes right 0, otherwise an error code.
Definition at line 129 of file pf_administration.c.
References BLACKLIST_FLAG, DB_FILE, ERR_FLAG, MAX_LINE_LENGTH, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, WHITELIST_FLAG, and write_logentry().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.