.TH "pf_administration.c" 3 "15 Dec 2008" "Version v0.02" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pf_administration.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <syslog.h>\fP
.br
\fC#include <sqlite3.h>\fP
.br
\fC#include 'libphonefirewall.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBevaluate_stmt\fP (sqlite3_stmt *pp_stmt, struct \fBEntry\fP *p_entry)"
.br
.ti -1c
.RI "int \fBevaluate_stmt_string\fP (sqlite3_stmt *pp_stmt, char *number, int priority)"
.br
.ti -1c
.RI "int \fBadd_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority, int listflag)"
.br
.ti -1c
.RI "int \fBrm_entry\fP (int country_code, int area_code, unsigned long long number, int listflag)"
.br
.ti -1c
.RI "int \fBcheck_entry\fP (int country_code, int area_code, unsigned long long number, int priority, int listflag)"
.br
.ti -1c
.RI "int \fBcheck_entry_string\fP (char *number, int priority, int listflag)"
.br
.ti -1c
.RI "int \fBchange_name\fP (int country_code, int area_code, unsigned long long number, char *new_name, int listflag)"
.br
.ti -1c
.RI "int \fBchange_number\fP (int country_code, int area_code, unsigned long long number, int new_country_code, int new_area_code, unsigned long long new_number, int listflag)"
.br
.ti -1c
.RI "int \fBchange_reason\fP (int country_code, int area_code, unsigned long long number, char *new_reason, int listflag)"
.br
.ti -1c
.RI "int \fBchange_priority\fP (int country_code, int area_code, unsigned long long number, int new_priority, int listflag)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int add_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority, int listflag)"
.PP
Add a number to the blacklist/whitelist. The number will be blocked after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
The value 'PRIO_ALL' stands for all priorities.
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise -1 and the errno variable will be set.. 
.RE
.PP

.PP
Definition at line 111 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and WHITELIST_FLAG.
.SS "int change_name (int country_code, int area_code, unsigned long long number, char * new_name, int listflag)"
.PP
Changes the name of the \fBentry\fP. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the \fBentry\fP.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fInew_name\fP The new name 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was changed 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 313 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, and WHITELIST_FLAG.
.SS "int change_number (int country_code, int area_code, unsigned long long number, int new_country_code, int new_area_code, unsigned long long new_number, int listflag)"
.PP
Changes the number of the \fBentry\fP. You need to enter the country code, area code and the number because this tripple identifies the \fBentry\fP.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fInew_country_code\fP The new country code. 
.br
\fInew_area_code\fP The new area code. 
.br
\fInew_number\fP The new number. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was changed 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 348 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and WHITELIST_FLAG.
.SS "int change_priority (int country_code, int area_code, unsigned long long number, int new_priority, int listflag)"
.PP
Changes the priority of the \fBentry\fP. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the \fBentry\fP.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fInew_priority\fP The new priority. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was changed 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 420 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
.SS "int change_reason (int country_code, int area_code, unsigned long long number, char * new_reason, int listflag)"
.PP
Changes the reason of the \fBentry\fP. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the \fBentry\fP.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fInew_reason\fP The new reason. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was changed 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 385 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_REASON, and WHITELIST_FLAG.
.SS "int check_entry (int country_code, int area_code, unsigned long long number, int priority, int listflag)"
.PP
Checks if a number is on the blacklist/whitelist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
The value 'PRIO_ALL' stands for all priorities.
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 186 of file pf_administration.c.
.PP
References Entry::area_code, BLACKLIST_FLAG, COMPONENT_NAME, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
.SS "int check_entry_string (char * number, int priority, int listflag)"
.PP
Checks if a number is on the blacklist/whitelist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The whole number with country code, area code and phone number. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 254 of file pf_administration.c.
.PP
References BLACKLIST_FLAG, COMPONENT_NAME, DB_FILE, evaluate_stmt_string(), STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
.SS "int evaluate_stmt (sqlite3_stmt * pp_stmt, struct \fBEntry\fP * p_entry)"
.PP
Definition at line 28 of file pf_administration.c.
.PP
References Entry::area_code, Entry::country_code, Entry::number, PRIO_ALL, Entry::priority, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.PP
Referenced by check_entry().
.SS "int evaluate_stmt_string (sqlite3_stmt * pp_stmt, char * number, int priority)"
.PP
Definition at line 74 of file pf_administration.c.
.PP
References PRIO_ALL, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.PP
Referenced by check_entry_string().
.SS "int rm_entry (int country_code, int area_code, unsigned long long number, int listlfag)"
.PP
Removes a number from the blacklist/whitelist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The number which will be deleted. 
.br
\fIlistflag\fP A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
.br
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 153 of file pf_administration.c.
.PP
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and WHITELIST_FLAG.
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
