pf_administration.c
NAME
pf_administration.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <syslog.h>
#include <sqlite3.h>
#include 'libphonefirewall.h'
Functions
int evaluate_stmt (sqlite3_stmt *pp_stmt, struct Entry *p_entry)
int evaluate_stmt_string (sqlite3_stmt *pp_stmt, char *number, int priority)
int add_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority, int listflag)
int rm_entry (int country_code, int area_code, unsigned long long number, int listflag)
int check_entry (int country_code, int area_code, unsigned long long number, int priority, int listflag)
int check_entry_string (char *number, int priority, int listflag)
int change_name (int country_code, int area_code, unsigned long long number, char *new_name, int listflag)
int change_number (int country_code, int area_code, unsigned long long number, int new_country_code, int new_area_code, unsigned long long new_number, int listflag)
int change_reason (int country_code, int area_code, unsigned long long number, char *new_reason, int listflag)
int change_priority (int country_code, int area_code, unsigned long long number, int new_priority, int listflag)
Function Documentation
int add_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority, int listflag)
Add a number to the blacklist/whitelist. The number will be blocked after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
The value 'PRIO_ALL' stands for all priorities.
Returns:
If all goes well 0 (zero) otherwise -1 and the errno variable will be set..
Definition at line 111 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and WHITELIST_FLAG.
int change_name (int country_code, int area_code, unsigned long long number, char * new_name, int listflag)
Changes the name of the entry. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the entry.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
new_name The new name
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If the number was changed 1, otherwise 0.
Definition at line 313 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, and WHITELIST_FLAG.
int change_number (int country_code, int area_code, unsigned long long number, int new_country_code, int new_area_code, unsigned long long new_number, int listflag)
Changes the number of the entry. You need to enter the country code, area code and the number because this tripple identifies the entry.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
new_country_code The new country code.
new_area_code The new area code.
new_number The new number.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If the number was changed 1, otherwise 0.
Definition at line 348 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and WHITELIST_FLAG.
int change_priority (int country_code, int area_code, unsigned long long number, int new_priority, int listflag)
Changes the priority of the entry. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the entry.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
new_priority The new priority.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If the number was changed 1, otherwise 0.
Definition at line 420 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
int change_reason (int country_code, int area_code, unsigned long long number, char * new_reason, int listflag)
Changes the reason of the entry. For the unique identification you need to enter the country code, area code and the number because this tripple identifies the entry.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
new_reason The new reason.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If the number was changed 1, otherwise 0.
Definition at line 385 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_REASON, and WHITELIST_FLAG.
int check_entry (int country_code, int area_code, unsigned long long number, int priority, int listflag)
Checks if a number is on the blacklist/whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
The value 'PRIO_ALL' stands for all priorities.
Returns:
If the number was found 1, otherwise 0.
Definition at line 186 of file pf_administration.c.
References Entry::area_code, BLACKLIST_FLAG, COMPONENT_NAME, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
int check_entry_string (char * number, int priority, int listflag)
Checks if a number is on the blacklist/whitelist.
Parameters:
number The whole number with country code, area code and phone number.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If the number was found 1, otherwise 0.
Definition at line 254 of file pf_administration.c.
References BLACKLIST_FLAG, COMPONENT_NAME, DB_FILE, evaluate_stmt_string(), STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, TB_PRIORITY, and WHITELIST_FLAG.
int evaluate_stmt (sqlite3_stmt * pp_stmt, struct Entry * p_entry)
Definition at line 28 of file pf_administration.c.
References Entry::area_code, Entry::country_code, Entry::number, PRIO_ALL, Entry::priority, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
Referenced by check_entry().
int evaluate_stmt_string (sqlite3_stmt * pp_stmt, char * number, int priority)
Definition at line 74 of file pf_administration.c.
References PRIO_ALL, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
Referenced by check_entry_string().
int rm_entry (int country_code, int area_code, unsigned long long number, int listlfag)
Removes a number from the blacklist/whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The number which will be deleted.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
If all goes right 0, otherwise an error code.
Definition at line 153 of file pf_administration.c.
References COMPONENT_NAME, DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and WHITELIST_FLAG.
Author
Generated automatically by Doxygen for Phone Firewall from the source code.