pf_daemon.c
NAME
pf_daemon.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <stdbool.h>
#include <dbus/dbus.h>
#include 'libphonefirewall.h'
Defines
#define LOCKFILE '.lock'
Functions
void start_daemon ()
void stop_daemon ()
void dbus_listen ()
int main (int argc, char **argv)
Define Documentation
#define LOCKFILE '.lock'
Definition at line 9 of file pf_daemon.c.
Referenced by start_daemon(), and stop_daemon().
Function Documentation
void dbus_listen ()
Function that provides method calls.
Bus name: to.networld.moksec.phonefirewall Object name: to.networld.moksec.phonefirewall.Object interface: to.networld.moksec.phonefirewall.Checking methods: checkblacklist(...) checkwhitelist(...)
Definition at line 75 of file pf_daemon.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 34 of file pf_daemon.c.
References dbus_listen(), start_daemon(), and stop_daemon().
void start_daemon ()
Starts the program as a daemon and creates a lockfile (specified in the LOCKFILE constant). So it's impossible to start the daemon twice.
Definition at line 45 of file pf_daemon.c.
References LOCKFILE.
Referenced by main().
void stop_daemon ()
Stops the daemon and deletes the lockfile, so a new instance can be started.
Definition at line 69 of file pf_daemon.c.
References LOCKFILE.
Referenced by main().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.