.TH "pf_daemon.c" 3 "8 Jun 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pf_daemon.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <stdbool.h>\fP
.br
\fC#include <dbus/dbus.h>\fP
.br
\fC#include 'pf_daemon.h'\fP
.br
\fC#include 'libphonefirewall.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_daemon\fP ()"
.br
.ti -1c
.RI "void \fBstop_daemon\fP ()"
.br
.ti -1c
.RI "void \fBdbus_listen\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dbus_listen ()"
.PP
Definition at line 57 of file pf_daemon.c.
.PP
Referenced by main().
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 16 of file pf_daemon.c.
.PP
References dbus_listen(), start_daemon(), and stop_daemon().
.SS "void start_daemon ()"
.PP
Definition at line 27 of file pf_daemon.c.
.PP
References LOCKFILE.
.PP
Referenced by main().
.SS "void stop_daemon ()"
.PP
Definition at line 51 of file pf_daemon.c.
.PP
References LOCKFILE.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
