.TH "pf_daemon.h" 3 "14 Jul 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pf_daemon.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOCKFILE\fP   '.lock'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_daemon\fP ()"
.br
.ti -1c
.RI "void \fBstop_daemon\fP ()"
.br
.ti -1c
.RI "void \fBdbus_listen\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOCKFILE   '.lock'"
.PP
Definition at line 21 of file pf_daemon.h.
.PP
Referenced by start_daemon(), and stop_daemon().
.SH "Function Documentation"
.PP 
.SS "void dbus_listen ()"
.PP
Function that provides method calls.
.PP
Bus name: to.networld.moksec.phonefirewall Object name: to.networld.moksec.phonefirewall.Object interface: to.networld.moksec.phonefirewall.Checking methods: checkblacklist(...) checkwhitelist(...) 
.SS "void start_daemon ()"
.PP
Starts the program as a daemon and creates a lockfile (specified in the LOCKFILE constant). So it's impossible to start the daemon twice. 
.SS "void stop_daemon ()"
.PP
Stops the daemon and deletes the lockfile, so a new instance can be started. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
