.TH "pf_daemon.c" 3 "13 Jul 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pf_daemon.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <stdbool.h>\fP
.br
\fC#include <dbus/dbus.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include 'pf_daemon.h'\fP
.br
\fC#include 'libphonefirewall.h'\fP
.br
\fC#include 'logfile.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_daemon\fP ()"
.br
.ti -1c
.RI "void \fBstop_daemon\fP ()"
.br
.ti -1c
.RI "void \fBdbus_listen\fP ()"
.br
.ti -1c
.RI "void \fBinstall_sigaction\fP ()"
.br
.ti -1c
.RI "void \fBreact_to_signal\fP (int sig)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dbus_listen ()"
.PP
Definition at line 87 of file pf_daemon.c.
.PP
References ERR_FLAG, INFO_FLAG, and write_logentry().
.PP
Referenced by main().
.SS "void install_sigaction ()"
.PP
Definition at line 143 of file pf_daemon.c.
.PP
References react_to_signal().
.PP
Referenced by main().
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 38 of file pf_daemon.c.
.PP
References dbus_listen(), install_sigaction(), start_daemon(), and stop_daemon().
.SS "void react_to_signal (int sig)"
.PP
Definition at line 157 of file pf_daemon.c.
.PP
References stop_daemon().
.PP
Referenced by install_sigaction().
.SS "void start_daemon ()"
.PP
Definition at line 53 of file pf_daemon.c.
.PP
References INFO_FLAG, LOCKFILE, and write_logentry().
.PP
Referenced by main().
.SS "void stop_daemon ()"
.PP
Definition at line 79 of file pf_daemon.c.
.PP
References INFO_FLAG, LOCKFILE, and write_logentry().
.PP
Referenced by main(), and react_to_signal().
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
