pf_search.c
NAME
pf_search.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sqlite3.h>
#include 'libphonefirewall.h'
Defines
#define ASCII_PERCENT_CHAR 37
Functions
struct Entry * insert_into_list (struct Entry *p_root, struct Entry *p_entry)
struct Entry * find_entry (sqlite3_stmt *pp_stmt)
struct Entry * get_entry_by_name (char *name, int listflag)
struct Entry * get_entry_by_number (int country_code, int area_code, unsigned long long number, int listflag)
struct Entry * get_entry_by_reason (char *reason, int listflag)
Define Documentation
#define ASCII_PERCENT_CHAR 37
Definition at line 27 of file pf_search.c.
Referenced by get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
Function Documentation
struct Entry* find_entry (sqlite3_stmt * pp_stmt) [read]
Definition at line 76 of file pf_search.c.
References Entry::area_code, Entry::country_code, Entry::name, Entry::number, Entry::priority, Entry::reason, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
Referenced by get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
struct Entry* get_entry_by_name (char * name, int listflag) [read]
Search a entry by name.
Parameters:
name The name of the person which is blocked.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
entry Returns the entries which are found in a linked list.
Definition at line 112 of file pf_search.c.
References ASCII_PERCENT_CHAR, DB_FILE, ERR_LOG, find_entry(), insert_into_list(), MAX_LINE_LENGTH, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and WHITELIST_FLAG.
struct Entry* get_entry_by_number (int country_code, int area_code, unsigned long long number, int listflag) [read]
Search a entries by number (country code + area code + number).
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
entry Returns the entries which are found in a linked list.
Definition at line 158 of file pf_search.c.
References ASCII_PERCENT_CHAR, DB_FILE, ERR_LOG, find_entry(), insert_into_list(), MAX_LINE_LENGTH, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and WHITELIST_FLAG.
struct Entry* get_entry_by_reason (char * reason, int listflag) [read]
Search a entries by reason.
Parameters:
reason The reason why a person is blocked/accpeted.
listflag A flag, which indicates if you would use the blacklist (BLACKLIST_FLAG) or the whitelist (WHITELIST_FLAG).
Returns:
entry Returns the entries which are found in a linked list.
Definition at line 206 of file pf_search.c.
References ASCII_PERCENT_CHAR, DB_FILE, ERR_LOG, find_entry(), insert_into_list(), MAX_LINE_LENGTH, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and WHITELIST_FLAG.
struct Entry* insert_into_list (struct Entry * p_root, struct Entry * p_entry) [read]
Definition at line 29 of file pf_search.c.
References Entry::area_code, Entry::country_code, Entry::name, Entry::next, Entry::number, and Entry::reason.
Referenced by get_entry_by_name(), get_entry_by_number(), and get_entry_by_reason().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.