phonefirewall_search.c
NAME
phonefirewall_search.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sqlite3.h>
#include 'libphonefirewall.h'
#include 'logfile.h'
Defines
#define ASCII_PERCENT_CHAR 37
#define MAX_ENTRY_ARRAY 1024
Functions
struct Entry * find_entry_by_name (sqlite3_stmt *pp_stmt, char *name)
struct Entry * get_blacklist_entry_by_name (char *name)
struct Entry * get_blacklist_entry_by_number (int country_code, int area_code, unsigned long long number)
struct Entry * get_whitelist_entry_by_name (char *name)
struct Entry * get_whitelist_entry_by_number (int country_code, int area_code, unsigned long long number)
Variables
struct Entry * p_entry = &entry
struct Entry entry_array [MAX_ENTRY_ARRAY]
Define Documentation
#define ASCII_PERCENT_CHAR 37
Definition at line 28 of file phonefirewall_search.c.
Referenced by get_blacklist_entry_by_name().
#define MAX_ENTRY_ARRAY 1024
Definition at line 29 of file phonefirewall_search.c.
Function Documentation
struct Entry* find_entry_by_name (sqlite3_stmt * pp_stmt, char * name) [read]
Definition at line 34 of file phonefirewall_search.c.
References Entry::area_code, Entry::country_code, Entry::name, Entry::number, Entry::priority, Entry::reason, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
Referenced by get_blacklist_entry_by_name().
struct Entry* get_blacklist_entry_by_name (char * name) [read]
Search a entrie by name.
Parameters:
name The name of the person which is blocked.
Returns:
entry Returns the found entry.
Definition at line 66 of file phonefirewall_search.c.
References Entry::area_code, ASCII_PERCENT_CHAR, Entry::country_code, DB_FILE, entry_array, ERR_FLAG, find_entry_by_name(), MAX_LINE_LENGTH, Entry::number, Entry::reason, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, TB_REASON, and write_logentry().
struct Entry* get_blacklist_entry_by_number (int country_code, int area_code, unsigned long long number) [read]
Search a entrie by number (country code + area code + number).
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
Returns:
entry Returns the found entry.
Definition at line 115 of file phonefirewall_search.c.
struct Entry* get_whitelist_entry_by_name (char * name) [read]
Search a entrie by name.
Parameters:
name The name of the person which is accepted.
Returns:
entry Returns the found entry.
Definition at line 122 of file phonefirewall_search.c.
struct Entry* get_whitelist_entry_by_number (int country_code, int area_code, unsigned long long number) [read]
Search a entrie by number (country code + area code + number).
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
Returns:
entry Returns the found entry.
Definition at line 127 of file phonefirewall_search.c.
Variable Documentation
struct Entry entry_array[MAX_ENTRY_ARRAY]
Definition at line 32 of file phonefirewall_search.c.
Referenced by get_blacklist_entry_by_name().
struct Entry* p_entry = &entry
Definition at line 31 of file phonefirewall_search.c.
Referenced by check_blacklist_entry(), and check_whitelist_entry().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.