.TH "phonefirewall_administration.c" 3 "17 May 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phonefirewall_administration.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'libphonefirewall.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBLACKLIST_PREFIX\fP   'db/blacklist_'"
.br
.ti -1c
.RI "#define \fBWHITELIST_PREFIX\fP   'db/whitelist_'"
.br
.ti -1c
.RI "#define \fBFILENAME_SIZE\fP   256"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBset_filename\fP (char *prefix, int country_code, int area_code)"
.br
.ti -1c
.RI "int \fBadd_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "int \fBadd_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "int \fBrm_blacklist_entry\fP (unsigned long long number)"
.br
.ti -1c
.RI "int \fBrm_whitelist_entry\fP (unsigned long long number)"
.br
.ti -1c
.RI "char * \fBcheck_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.ti -1c
.RI "char * \fBcheck_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char * \fBDELIM\fP = '::'"
.br
.ti -1c
.RI "char \fBfilename\fP [FILENAME_SIZE]"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BLACKLIST_PREFIX   'db/blacklist_'"
.PP
Definition at line 26 of file phonefirewall_administration.c.
.PP
Referenced by add_blacklist_entry(), and check_blacklist_entry().
.SS "#define FILENAME_SIZE   256"
.PP
Definition at line 28 of file phonefirewall_administration.c.
.SS "#define WHITELIST_PREFIX   'db/whitelist_'"
.PP
Definition at line 27 of file phonefirewall_administration.c.
.PP
Referenced by add_whitelist_entry(), and check_whitelist_entry().
.SH "Function Documentation"
.PP 
.SS "int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the blacklist. The number will be blocked after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 40 of file phonefirewall_administration.c.
.PP
References BLACKLIST_PREFIX, DELIM, filename, and set_filename().
.SS "int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the whitelist. The number will be accepted after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 54 of file phonefirewall_administration.c.
.PP
References DELIM, filename, set_filename(), and WHITELIST_PREFIX.
.SS "char* check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.RE
.PP
\fBReturns:\fP
.RS 4
If noting is found NULL, otherwise the number. 
.RE
.PP

.PP
Definition at line 76 of file phonefirewall_administration.c.
.PP
References BLACKLIST_PREFIX, DELIM, filename, MAX_LINE_LENGTH, and set_filename().
.SS "char* check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.RE
.PP
\fBReturns:\fP
.RS 4
If noting is found NULL, otherwise the number. 
.RE
.PP

.PP
Definition at line 110 of file phonefirewall_administration.c.
.PP
References DELIM, filename, MAX_LINE_LENGTH, set_filename(), and WHITELIST_PREFIX.
.SS "int rm_blacklist_entry (unsigned long long number)"
.PP
Removes a blocked number from the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 68 of file phonefirewall_administration.c.
.SS "int rm_whitelist_entry (unsigned long long number)"
.PP
Removes a accepted number from the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 72 of file phonefirewall_administration.c.
.SS "int set_filename (char * prefix, int country_code, int area_code)"
.PP
Definition at line 34 of file phonefirewall_administration.c.
.PP
References filename.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), and check_whitelist_entry().
.SH "Variable Documentation"
.PP 
.SS "char* \fBDELIM\fP = '::'\fC [static]\fP"
.PP
Definition at line 30 of file phonefirewall_administration.c.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), and check_whitelist_entry().
.SS "char \fBfilename\fP[FILENAME_SIZE]"
.PP
Definition at line 32 of file phonefirewall_administration.c.
.PP
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), and set_filename().
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
