phonefirewall_administration.c
NAME
phonefirewall_administration.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include 'libphonefirewall.h'
Defines
#define BLACKLIST_PREFIX 'db/blacklist_'
#define WHITELIST_PREFIX 'db/whitelist_'
#define FILENAME_SIZE 256
Functions
int set_filename (char *prefix, int country_code, int area_code)
int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)
int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)
int rm_blacklist_entry (unsigned long long number)
int rm_whitelist_entry (unsigned long long number)
char * check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)
char * check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)
Variables
static char * DELIM = '::'
char filename [FILENAME_SIZE]
Define Documentation
#define BLACKLIST_PREFIX 'db/blacklist_'
Definition at line 26 of file phonefirewall_administration.c.
Referenced by add_blacklist_entry(), and check_blacklist_entry().
#define FILENAME_SIZE 256
Definition at line 28 of file phonefirewall_administration.c.
#define WHITELIST_PREFIX 'db/whitelist_'
Definition at line 27 of file phonefirewall_administration.c.
Referenced by add_whitelist_entry(), and check_whitelist_entry().
Function Documentation
int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)
Add a number to the blacklist. The number will be blocked after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If all goes well 0 (zero) otherwise an errno code.
Definition at line 40 of file phonefirewall_administration.c.
References BLACKLIST_PREFIX, DELIM, filename, and set_filename().
int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)
Add a number to the whitelist. The number will be accepted after that.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
name The name of the person.
reason Why you have blocked this person.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If all goes well 0 (zero) otherwise an errno code.
Definition at line 54 of file phonefirewall_administration.c.
References DELIM, filename, set_filename(), and WHITELIST_PREFIX.
char* check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)
Checks if a number is on the blacklist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If noting is found NULL, otherwise the number.
Definition at line 76 of file phonefirewall_administration.c.
References BLACKLIST_PREFIX, DELIM, filename, MAX_LINE_LENGTH, and set_filename().
char* check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)
Checks if a number is on the whitelist.
Parameters:
country_code The country code (for example 39 for Italy, 43 for Austria, and so one)
area_code The area code which indicates your mobile operator.
number The telephone number of the person (without country and area code.
priority Gives the entry a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
Returns:
If noting is found NULL, otherwise the number.
Definition at line 110 of file phonefirewall_administration.c.
References DELIM, filename, MAX_LINE_LENGTH, set_filename(), and WHITELIST_PREFIX.
int rm_blacklist_entry (unsigned long long number)
Removes a blocked number from the blacklist.
Parameters:
number The number which will be deleted.
Returns:
If all goes right 0, otherwise an error code.
Definition at line 68 of file phonefirewall_administration.c.
int rm_whitelist_entry (unsigned long long number)
Removes a accepted number from the whitelist.
Parameters:
number The number which will be deleted.
Returns:
If all goes right 0, otherwise an error code.
Definition at line 72 of file phonefirewall_administration.c.
int set_filename (char * prefix, int country_code, int area_code)
Definition at line 34 of file phonefirewall_administration.c.
References filename.
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), and check_whitelist_entry().
Variable Documentation
char* DELIM = '::' [static]
Definition at line 30 of file phonefirewall_administration.c.
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), and check_whitelist_entry().
char filename[FILENAME_SIZE]
Definition at line 32 of file phonefirewall_administration.c.
Referenced by add_blacklist_entry(), add_whitelist_entry(), check_blacklist_entry(), check_whitelist_entry(), and set_filename().
Author
Generated automatically by Doxygen for Phone Firewall from the source code.