.TH "phonefirewall_administration.c" 3 "7 Jun 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phonefirewall_administration.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <sqlite3.h>\fP
.br
\fC#include 'libphonefirewall.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBevaluate_stmt\fP (sqlite3_stmt *pp_stmt, struct \fBEntry\fP *p_entry)"
.br
.ti -1c
.RI "int \fBadd_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "int \fBadd_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, char *name, char *reason, int priority)"
.br
.ti -1c
.RI "int \fBrm_blacklist_entry\fP (int country_code, int area_code, unsigned long long number)"
.br
.ti -1c
.RI "int \fBrm_whitelist_entry\fP (int country_code, int area_code, unsigned long long number)"
.br
.ti -1c
.RI "int \fBcheck_blacklist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.ti -1c
.RI "int \fBcheck_whitelist_entry\fP (int country_code, int area_code, unsigned long long number, int priority)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int add_blacklist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the blacklist. The number will be blocked after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen. 
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 73 of file phonefirewall_administration.c.
.PP
References DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
.SS "int add_whitelist_entry (int country_code, int area_code, unsigned long long number, char * name, char * reason, int priority)"
.PP
Add a number to the whitelist. The number will be accepted after that.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIname\fP The name of the person. 
.br
\fIreason\fP Why you have blocked this person. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes well 0 (zero) otherwise an errno code. 
.RE
.PP

.PP
Definition at line 108 of file phonefirewall_administration.c.
.PP
References DB_FILE, PRIO_ALL, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NAME, TB_NUMBER, TB_PRIORITY, and TB_REASON.
.SS "int check_blacklist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 210 of file phonefirewall_administration.c.
.PP
References Entry::area_code, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.SS "int check_whitelist_entry (int country_code, int area_code, unsigned long long number, int priority)"
.PP
Checks if a number is on the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fIcountry_code\fP The country code (for example 39 for Italy, 43 for Austria, and so one) 
.br
\fIarea_code\fP The area code which indicates your mobile operator. 
.br
\fInumber\fP The telephone number of the person (without country and area code. 
.br
\fIpriority\fP Gives the \fBentry\fP a priority. 0 is standard. If the priority is higher the value will be also blocked/accepted if a higher priority is choosen.
.br
 The value 'PRIO_ALL' stands for all priorities.
.RE
.PP
\fBReturns:\fP
.RS 4
If the number was found 1, otherwise 0. 
.RE
.PP

.PP
Definition at line 261 of file phonefirewall_administration.c.
.PP
References Entry::area_code, Entry::country_code, DB_FILE, evaluate_stmt(), Entry::number, Entry::priority, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.SS "int evaluate_stmt (sqlite3_stmt * pp_stmt, struct \fBEntry\fP * p_entry)"
.PP
Definition at line 27 of file phonefirewall_administration.c.
.PP
References Entry::area_code, Entry::country_code, Entry::number, PRIO_ALL, Entry::priority, TB_AREACODE, TB_COUNTRYCODE, TB_NUMBER, and TB_PRIORITY.
.PP
Referenced by check_blacklist_entry(), and check_whitelist_entry().
.SS "int rm_blacklist_entry (int country_code, int area_code, unsigned long long number)"
.PP
Removes a blocked number from the blacklist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 143 of file phonefirewall_administration.c.
.PP
References DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, and TB_NUMBER.
.SS "int rm_whitelist_entry (int country_code, int area_code, unsigned long long number)"
.PP
Removes a accepted number from the whitelist.
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP The number which will be deleted.
.RE
.PP
\fBReturns:\fP
.RS 4
If all goes right 0, otherwise an error code. 
.RE
.PP

.PP
Definition at line 176 of file phonefirewall_administration.c.
.PP
References DB_FILE, STMT_SIZE, TB_AREACODE, TB_COUNTRYCODE, and TB_NUMBER.
.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
