.TH "whitelist" 3 "10 May 2008" "Version v0.01" "Phone Firewall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
whitelist \- Contains the accepted numbers.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libphonefirewall.h>\fP
.PP
.SH "Detailed Description"
.PP 
Contains the accepted numbers. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Phone Firewall from the source code.
